### ISSUE TITLE
[FEATURE] Sessions

### ISSUE THREAD

**Issue by maxogod** [maxogod/Truco#16]
## 🚀 Feature

Keep open sessions in the database

### Motivation

Sessions are important so that users don't have to log in every time they close and open the page again

### Implementation

Store a session id in the database in a `'Sessions' cluster` and send that id to the frontend in a cookie, so that as long as that cookie is in the browser and that id is in the database the user wont have to re-log in

**Comment by MelnikAndres** [comment]
Could you explain more? This way sounds unsecure, i think it would be better to have refresh and access tokens.

**Comment by maxogod** [comment]
@MelnikAndres SessionIDs are used widely in the market, an example of a big company that uses them is Youtube. But if your concern is security you don't have to worry as the only way for someone to 'steal' your session is if they somehow got your cookies, which should *not* happen anyway. For instance if you go to Youtube, log in and then transfer all your cookies to another Youtube tab you'll see that you will get access to that account without loging in. In conclusion, it's not insecure and it's a widely used solution to keep user sessions.
