### ISSUE TITLE
[FEATURE] Game board

### ISSUE THREAD

**Issue by JorgeSedek** [maxogod/Truco#2]
### Motivation

A game board will be useful to the players in order to have a better experience playing the game and it'll make it easier to play.

### Implementation

 there will be:

* four buttons which include the actions in the game: 
-- Envido
-- Truco
-- Flor
-- Mazo

* table and both player's cards on opposite sides of the table (the opponent's cards should be face down)
* the score in a notepad on the table
* played cards will appear face up, showing the winning card on top

### Additional context

![tablero](https://github.com/maxogod/Truco/assets/85034225/9b69af1f-fd1d-4d5c-9e78-af5ad15d1c24)

**Comment by maxogod** [comment]
@JorgeSedek Edite el issue para arreglar un poco de ortografia y saque la informacion que yo considere que no venia al caso para crear el tablero, como el funcionamiento del truco, retruco y vale cuatro. 

*aca dejo la anterior version del issue por las dudas:*

## 🚀 Feature

 A game board where the players could make their play. 

(Write your description here)

### Motivation

 

(Outline your motivation here)

A game board ll be useful to the players to have a better experience playing the game and ll be more easy to play.

### Implementation


 there ll be:
* four botons wich includes the actions in the game: 
-Envido: At the beginning of the game, a player can choose to envido.
-Truco: its for determining the points that the winner ll optain. There are four options: "truco" (2 points), "retruco" (3 points) and "vale --cuatro"(4 points). At the begining of each game, a player ll be selected to use the option of "truco", then the other player can choose to "retruco" and then the option returns to the first player to "vale cuatro" or not. 
-Flor:
Mazo: to abandon the game.
*two players and their respectives hands with 3 cards.
*the score.
*chat.

### Additional context
Add any other context or screenshots about the feature request here.
![tablero](https://github.com/maxogod/Truco/assets/85034225/9b69af1f-fd1d-4d5c-9e78-af5ad15d1c24)

**Comment by MelnikAndres** [comment]
Action buttons are taking too much space in this prototype, there is enough free space to include the buttons directly on the game view. Also, having action buttons separated from the game view makes it feel like we are controlling a player instead of being the player.
