### ISSUE TITLE
[FEATURE] Challenge Friends

### ISSUE THREAD

**Issue by maxogod** [maxogod/Truco#22]
### Motivation

Users should be able to challenge their friends and they should be able to accept or deny it

### Implementation

Similarly to the friend requests #21, there could be a field for incoming challenges in the User documents in the database, which will be updated with every received challenge (I don't know if it's a viable solution but if the assignee is not convinced we can discuss this further in a meeting)

**Comment by MelnikAndres** [comment]
Unless you want to challenge an offline friend (which i don't think it's necessary), you can do this with websocket, because there is no need to store that data in the database.
In case you do want to challenge offline friends, then storing the challenge in the database will be ok.

**Comment by maxogod** [comment]
> Unless you want to challenge an offline friend (which i don't think it's necessary), you can do this with websocket, because there is no need to store that data in the database. In case you do want to challenge offline friends, then storing the challenge in the database will be ok.

Don't worry the implementation detail i added was just a suggestion of a possible solution to explore, when we are closer to the implementation date of this issue we will discuss and try to find the best solution. But the priority of this issue is 4/5 so it won't be implemented yet
