### ISSUE TITLE
[FEATURE] Match log

### ISSUE THREAD

**Issue by maxogod** [maxogod/Truco#26]
## 🚀 Feature

a log that shows all the match's moves

### Motivation

It will make it easier for the players to follow what's going on and predict more accurately their point losses/gains

### Implementation

It should be logged to the game chat #12, in a different color, font or font weight from the rest of messages.

The log does not need to be kept anywhere once the match ends.

**Comment by MelnikAndres** [comment]
I don't think this fits the essence of the game, forgetting a move is player's fault.
What i think is better would be to just display the last move, in case the player was afk.

**Comment by maxogod** [comment]
This issue was created because it was a feature we decided would be nice to have, if you don't agree we can discuss this further in our next planning meeting.

> I don't think this fits the essence of the game, forgetting a move is player's fault. What i think is better would be to just display the last move, in case the player was afk.
