### ISSUE TITLE
[FEATURE] Surrender

### ISSUE THREAD

**Issue by maxogod** [maxogod/Truco#27]
### Motivation

Surrender from a match (counts as a loss)

### Implementation

Button will be on the bottom of the "play now" button and will only be visible when the user is in a match. Its color ll be red.
Clicking it will terminate the match granting the other player the victory and he ll gain 15 points.

**Comment by JorgeSedek** [comment]
As a team we decided to change the specs of this issue to look nicer to the user. Nonetheless, we did the previous implemention and decided to change it for this one because of the reason we explained above.
