### ISSUE TITLE
[DESIGN] Game board

### ISSUE THREAD

**Issue by alenmonti** [maxogod/Truco#30]
## 🎨 Design

Game board

### Implementation

Only design (0 code).
Main board, chat, list of actions, score

### Additional context
![game](https://github.com/maxogod/Truco/assets/90219740/3b6e90c0-56b7-4a40-99e8-53e2f0baa8dc)

**Comment by MelnikAndres** [comment]
this prototype has too much things on screen and at the same time too much wasted space, we need to rearrange this view.

**Comment by maxogod** [comment]
> this prototype has too much things on screen and at the same time too much wasted space, we need to rearrange this view.

I repeat my reply in #2, the prototype exists to have a general idea of all the features we need to add, the design is yet to be done. DESIGN issues have already been created!
