### ISSUE TITLE
[FEATURE] Add turns for the players

### ISSUE THREAD

**Issue by JorgeSedek** [maxogod/Truco#4]
## 🚀 Feature

A system that will determine whose turn it is and will let only that player make their play.

### Motivation

In the game each player should have a turn to make their play and pass the turn to the other player, further details in the implementation title.

### Implementation

The first turn should be randomly assigned to one of the players and it should rotate after each round.

A round consists of 3 turns per player, and a player can play one card per turn before passing the turn to the other player.

Special events:

* In the first turn of both players (and only then) they can ask the other player if they want to play ENVIDO, once that happens the other player must be able to accept, deny or double down (ENVIDO ENVIDO, REAL ENVIDO, FALTA ENVIDO) it and whether it happens or not the turn still belongs to player 1 even after the ENVIDO
* When a player calls FLOR they get points (points will be covered in another issue) unless the other player also calls FLOR in which case they will play normally and the winner of the round will get double the points of FLOR. When the other player responds to FLOR with CONTRAFLOR the one with more accumulative points (accumulative points will be covered in another issue) wins the entire match. The ENVIDO will be disabled for the rest of the round
* Both players can call TRUCO at any point in the round if it's their turn, this will give the other player the opportunity to accept, deny or double down (RETRUCO, VALE CUATRO). Just like in ENVIDO the player who first called TRUCO will continue their turn in case the other player accepted, but in case either player denies any form of TRUCO they automatically lose the round
* When a player hits MAZO at any given moment they surrender the round no matter whose turn it was

**Comment by maxogod** [comment]
The issue was edited, here is a copy of the old one:

## 🚀 Feature



(Write your description here)

A system that ll determine whos turn it is and ll let only that player make his play.

### Motivation



(Outline your motivation here)

In the game each player have a turn to make his play.

### Implementation



### Additional context
Add any other context or screenshots about the feature request here.
