### ISSUE TITLE
[FEATURE] add a timer for each player.

### ISSUE THREAD

**Issue by JorgeSedek** [maxogod/Truco#5]
## 🚀 Feature

A timer for each player that will show how much time the player has to make his play.

### Motivation

It will avoid long games so the experience will be more fun.

### Implementation

In case of a player running out of time they will lose the round automatically, and if they timeout again the match will be granted to the other player

**Comment by MelnikAndres** [comment]
Losing the round automatically can interrupt the flow of the game, it would be better to force a random move.

**Comment by maxogod** [comment]
> Losing the round automatically can interrupt the flow of the game, it would be better to force a random move.

You wouldn't want to keep playing against a bot, would you? that's why when a player is afk they should lose that match, giving the other player the opportunity to quickly find a new match with a player who isn't afk

**Comment by MelnikAndres** [comment]
What you said is correct, but i was talking about the first "afk" move, it is common to miss a timer when playing this kind of games where timers are short for each move. Punishing too hard for an unintentional momentary afk will frustrate the player.

**Comment by maxogod** [comment]
> What you said is correct, but i was talking about the first "afk" move, it is common to miss a timer when playing this kind of games where timers are short for each move. Punishing too hard for an unintentional momentary afk will frustrate the player.

i understand your point, we can talk about it when we reach priority 4 :)
