### ISSUE TITLE
[FEATURE] add cards to the game.

### ISSUE THREAD

**Issue by JorgeSedek** [maxogod/Truco#7]
## 🚀 Feature

a card that will have a number (1-12) and a symbol (clubs, swords, cups and golden coins).

### Motivation

You need cards to play the game and this issue is necessary for the development of the game board #2 

### Implementation

If the art design is not available yet, just use mock cards with a number and a letter (representing the symbol) on them

**Comment by maxogod** [comment]
(edited), original issue:

## 🚀 Feature



(Write your description here)

a card that ll have a number(1-12) and a symbol (clubs, swords, cups and golden coins).

### Motivation



(Outline your motivation here)

you need cards to play the game.

### Implementation



### Additional context
Add any other context or screenshots about the feature request here.
