### ISSUE TITLE
[FEATURE] add a deck to the game.

### ISSUE THREAD

**Issue by JorgeSedek** [maxogod/Truco#8]
## 🚀 Feature

a deck of 40 cards (there are 50 cards in the Spanish deck but TRUCO uses 10 less, leaving out Jokers, 9s and 8s) which the player can draw from.

### Motivation

the player needs to draw new cards to play the game.

### Implementation

The cards should be randomly assigned to the players from a list of all 40 cards

**Comment by maxogod** [comment]
(edited), original issue:

## 🚀 Feature



(Write your description here)

a deck of 50 cards from wich the player can draw cards.

### Motivation



(Outline your motivation here)

the player needs to draw new cards to play the game.

### Implementation



### Additional context
Add any other context or screenshots about the feature request here.
